### ISSUE TITLE
Corda nodes PartyA/PartyB failing with ClassNotFoundException

### ISSUE THREAD

**Issue by v-bilous** [manosbatsis/corbeans-yo-cordapp#5]
Hello @manosbatsis , I'm currently learning the Corda to see if it's applicable to the Project I'm architecting. Happy to see such Framework you created for the Corda but unfortunately I'm facing the issue right now, see below:

Corda PartyX nodes cannot start with added Partiture dependency
When **_DeployNodes_** -> then _**Run**_ through the cordapp-workflow/build/nodes/runnodes
Nodes PartyA and PartyB failing with the _**java.lang.ClassNotFoundException: com.github.manosbatsis.partiture.flow.PartitureResponderFlow**_
See attached log. 
[fail.log](https://github.com/manosbatsis/corbeans-yo-cordapp/files/3483147/fail.log)

**Comment by manosbatsis** [comment]
Thanks for raising @vladimirbilous , fixed by changing the partiture dependency to `compile` at _cordapp-workflow/build.gradle_

**Comment by v-bilous** [comment]
no problem, @manosbatsis thanks for the fixing the issue.
