### ISSUE TITLE
Send/Get Yo doesn't work

### ISSUE THREAD

**Issue by v-bilous** [manosbatsis/corbeans-yo-cordapp#6]
Hello @manosbatsis, 
Sorry for disturbing you. I was able to start the nodes/server today but faced another issue. 
**This time seems like I figured out a solution about how to fix this.** 

**Subject**
Yo functionality doesn't work at all using endpoints _**http://localhost:8080/api/yo/partyA/yo?target=PartyB**_ to create Yo and _**http://localhost:8080/api/yo/partyA/yos**_ to get the list of Yos.
The exception that I caught says the following:
_net.corda.core.CordaRuntimeException: java.io.NotSerializableException: mypackage.cordapp.contract.YoContract$YoState was not found by the node, check the Node containing the CorDapp that implements mypackage.cordapp.contract.YoContract$YoState is loaded and on the Classpath_

**Solution**
I figured out that Cordapp with Contracts not appearing the in the nodes folder after the **_deployNodes_**. 
I've applied the following changes and it's solved the problem:
1. Add _nodeDefaults_ to the **_deployNodes_** task  in file _cordapp-workflow/build.gradle_ 
` nodeDefaults {
        cordapp project(":cordapp-contract")
    }`
2. As option, added to the Notary `projectCordapp { deploy = false }` to skip workflow cordapp including. 
Attaching my build.gradle file 

[build_gradle.txt](https://github.com/manosbatsis/corbeans-yo-cordapp/files/3487408/build_gradle.txt)

**Comment by manosbatsis** [comment]
Nice @vladimirbilous , thanks for the patch!
